package com.example.BusinessProfileManagement.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.example.BusinessProfileManagement.model.TaxInfo;
import com.example.BusinessProfileManagement.model.convertor.ProfileStatusConverter;
import com.example.BusinessProfileManagement.model.convertor.TaxInfoEncryptConverter;
import com.example.BusinessProfileManagement.model.enums.ProfileStatus;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;


@lombok.Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "business_profile")
@DynamoDBDocument
public class BusinessProfileEntity {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String profileId;
  @DynamoDBAttribute
  private String companyName;
  @DynamoDBAttribute
  private String legalName;
  @DynamoDBAttribute
  private AddressEntity businessAddress;
  @DynamoDBAttribute
  private AddressEntity legalAddress;
  @DynamoDBTypeConverted(converter = TaxInfoEncryptConverter.class)
  private TaxInfo taxInfoEntity;
  @DynamoDBAttribute
  private String email;
  @DynamoDBAttribute
  private String website;
//  @DynamoDBAttribute
//  private Long updateTime;
//  @DynamoDBAttribute
//  private Long creationTime;
  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = ProfileStatusConverter.class)
  private ProfileStatus status;

}