package com.example.BusinessProfileManagement.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.example.BusinessProfileManagement.model.convertor.ApprovalStatusConverter;
import com.example.BusinessProfileManagement.model.convertor.ProductSetConverter;
import com.example.BusinessProfileManagement.model.convertor.RequestTypeConverter;
import com.example.BusinessProfileManagement.model.enums.ApprovalStatus;
import com.example.BusinessProfileManagement.model.enums.RequestType;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;


@lombok.Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "business_profile_request")
public class BusinessProfileRequestEntity {
  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName = "requestId")
  private String requestId;

  @DynamoDBAttribute
  private String profileId;

  @DynamoDBAttribute
  private BusinessProfileEntity businessProfile;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = ApprovalStatusConverter.class)
  private ApprovalStatus status;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = RequestTypeConverter.class)
  private RequestType requestType;

  @DynamoDBAttribute
  private String comments;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = ProductSetConverter.class)
  private Set<String> subscriptions;
}
