package com.example.BusinessProfileManagement.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.example.BusinessProfileManagement.model.convertor.UUIDConverter;
import com.example.BusinessProfileManagement.model.enums.ApprovalStatus;
import com.example.BusinessProfileManagement.model.enums.Product;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MapKeyEnumerated;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "business_profile")
public class BusinessProfile {
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  @DynamoDBTypeConverted(converter = UUIDConverter.class)
  private UUID profileId;
  @DynamoDBAttribute
  private String companyName;
  @DynamoDBAttribute
  private String legalName;
  @DynamoDBAttribute
  private Address businessAddress;
  @DynamoDBAttribute
  private Address legalAddress;
  @DynamoDBAttribute
  private String pan;
  @DynamoDBAttribute
  private String ein;
  @DynamoDBAttribute
  private String email;
  @DynamoDBAttribute
  private String website;
  @DynamoDBAttribute
  private Long updateTime;
  @DynamoDBAttribute
  private Long creationTime;

  @DynamoDBAttribute
  private Set<Product> subscriptions = new HashSet<>();
  @DynamoDBAttribute
  private ApprovalStatus approvalStatus;
}